# GENRE CALLS #

@base_url=http://localhost:3000/api/genres
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzlhMDhiZjFhMjFlNmM0OWUyMGZjODgiLCJpYXQiOjE2NzEwMzkxOTZ9.oE6Yq_sZzUKKSX7k7KFxNKu1QTU5YqqYSODWtdzdc5k

post {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzlhMDhiZjFhMjFlNmM0OWUyMGZjODgiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzEwMzkzMTd9.GlCpUFCicM0B4r9FhEYMZKspRsetq8xsfp0BtUXywtA

{
    "name":"Horror"
}

###

post {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzliODYxMTgzMGY0NWQ0YjA0MmYwNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzExMzY3ODZ9.2N9jm2dwSO8HGjZ_i65KjqSeIO0487-ZwjLbhSOfzHQ

{
    "name":"testRacing"
}


###

post {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzliODFkODZhOGRmM2JiMzY3NjQ1YWYiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjcxMTM2MDg0fQ.5JVlLUsY8rF21pfxg7QRU9yf7SibtkKCieL3fa5gm5M

{
    "name":"testtest"
}
