# USER CALLS #

@base_url=http://20.4.219.159:3000/api/games
@tokenAD=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I2ZjllYzhiMDg2MTRlOGFkZTkxNTYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzI5MzU5MTZ9.5jwSFh48-uB3n7z0mfqaeWzS8zzPuqxEi9kBKaLj9lM

post {{base_url}}
Content-Type: application/json
x-auth-token: {{tokenAD}}

{
    "title":"Star Wars: Battlefront",
    "genreId":"63b6fb5b8b08614e8ade9162",
    "studioId":"63b5e645a592e42d8c7e08cc"
    
}

###

post {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I4NTA4YjlmOWUwZmYwMzY3NjNlNjUiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzMwMjYyNjV9.YbgV4BTX3mxUfBq30qknHDCErf3Jo5j2inuiZBBHe9U

{
    "title":"The Witcher 3: Wild Hunt",
    "genreId":"63b85ae5eb6ae3bd20330254",
    "studioId":"63b850f39f9e0ff036763e6a"
    
}

### 

@objId=639b8dbf6763034c6cedfb22
delete {{base_url}}/{{objId}}
Content-Type: application/json
x-auth-token: {{tokenAD}}

###

@objId2=63b5e0b132bb75bef1b79440

get {{base_url}}/{{objId2}}
Content-Type: application/json

###
get {{base_url}}
Content-Type: application/json

