# GENRE CALLS #

@base_url=http://localhost:3000/api/genres

@tokenAD=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FmMjM2YjZjYzExMTQ5OTlhN2FhYmMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzI0MjIyNTF9.n69Fw0INihKYHtayfi0-46MRl6pr0n-WfePQp-w97e4
post {{base_url}}
Content-Type: application/json
x-auth-token: {{tokenAD}}

{
    "name":"RPG"
}

###

@objId=639a09d13b1c83fb41dc364f
put {{base_url}}/{{objId}}
Content-Type: application/json
x-auth-token: {{tokenAD}}

{
    "name":"Simulator"
}

###

@objId2=639a0aca8a545ec56a298438

delete {{base_url}}/{{objId2}}
Content-Type: application/json
x-auth-token: {{tokenAD}}
