# Studio Calls #

@base_url= http://20.4.219.159:3000/api/studios
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I4NTA4YjlmOWUwZmYwMzY3NjNlNjUiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzMwMjM2ODF9.B43Rhjvuvahrkcmeub3nI2mKvvYfKq4MOi8I1L6wIlM


post {{base_url}}
Content-Type: application/json
x-auth-token: {{token}}

{
    "name":"EA Games",
    "location":"New York"
    
}

###

post {{base_url}}
Content-Type: application/json
x-auth-token: {{token}}

{
    "name":"CD Project Red",
    "location":"Warsaw"
    
}

###
put {{base_url}}/63b5e645a592e42d8c7e08cc
Content-Type: application/json
x-auth-token:{{token}}

{
    "name":"EA Games",
    "location":"Vancouver"
}

###
@objId=63b5e645a592e42d8c7e08cc

get {{base_url}}/{{objId}}
Content-Type: application/json

###
get {{base_url}}
Content-Type: application/json