# USER CALLS #

@base_url=http://localhost:3000/api/games
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzliODYxMTgzMGY0NWQ0YjA0MmYwNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzE1NDE3MDN9.SijXTFo9zRoHmA4zu6by6T0t7d0MYlxMfB0GEhBIIWM

post {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzliODYxMTgzMGY0NWQ0YjA0MmYwNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzExMzcwNjF9.MUGU8qnUTZjhORDbLaC9u_csadMWaqwO00pZvsF6Z94

{
    "title":"Need For Speed",
    "genreId":"639a0d156bac7e7ca6907195",
    "studioId":"639b8749830f45d4b042f066"
    
}

###

post {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzliODYxMTgzMGY0NWQ0YjA0MmYwNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzExMzcwNjF9.MUGU8qnUTZjhORDbLaC9u_csadMWaqwO00pZvsF6Z94

{
    "title":"The Witcher 3: Wild Hunt",
    "genreId":"6398eb0969baa19f93fa5834",
    "studioId":"639dcec46763034c6cedfb26"
    
}

### 

@objId=639b8dbf6763034c6cedfb22
delete {{base_url}}/{{objId}}
Content-Type: application/json
x-auth-token: {{token}}

###

@objId2=639dcefb6763034c6cedfb2a

get {{base_url}}/{{objId2}}
Content-Type: application/json

###
get {{base_url}}
Content-Type: application/json
