# GENRE CALLS #

@base_url=http://localhost:3000/api/genres

@tokenAD=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I1Y2JiZjVhOTdhMjZkMGM2Zjg5MjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzI4NTg1NTl9.r_fd7eu6ryKCnwiDHg2gp3haDBnHNOCdWIEC74VBokE
post {{base_url}}
Content-Type: application/json
x-auth-token: {{tokenAD}}

{
    "name":"RPG"
}

###

@objId=639a09d13b1c83fb41dc364f
put {{base_url}}/{{objId}}
Content-Type: application/json
x-auth-token: {{tokenAD}}

{
    "name":"Simulator"
}

###

@objId2=639a0aca8a545ec56a298438

delete {{base_url}}/{{objId2}}
Content-Type: application/json
x-auth-token: {{tokenAD}}
