# Studio Calls #

@base_url= http://localhost:3000/api/studios
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzliODYxMTgzMGY0NWQ0YjA0MmYwNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzExMzcwNjF9.MUGU8qnUTZjhORDbLaC9u_csadMWaqwO00pZvsF6Z94

post {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzliODYxMTgzMGY0NWQ0YjA0MmYwNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzExMzcwNjF9.MUGU8qnUTZjhORDbLaC9u_csadMWaqwO00pZvsF6Z94

{
    "name":"EA Games",
    "location":"New York"
    
}

###

post {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzliODYxMTgzMGY0NWQ0YjA0MmYwNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzE3OTc0NDF9.zGpim1Hu_rurvyaBe2UO48VuHyYI17Kj55r6099aSWQ

{
    "name":"CD Project Red",
    "location":"Warsaw"
    
}

###
@objId=639b8749830f45d4b042f066
put {{base_url}}/{{objId}}
Content-Type: application/json
x-auth-token:{{token}}

{
    "name":"EA Games",
    "location":"Vancouver"
}

###
@objId=639b8749830f45d4b042f066

get {{base_url}}/{{objId}}
Content-Type: application/json

###
get {{base_url}}
Content-Type: application/json