#Library calls#



@base_url = http://localhost:3000/api/libraries

###
post {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FmMjM2YjZjYzExMTQ5OTlhN2FhYmMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzI4NTQzNzB9.bXUf0hDfrCb4LKwHrm_vPaXusAEN6rahe_KJ9aMHfSA

{
    "user":"63af236b6cc1114999a7aabc"
}

###
@objId = "63b5c03ce2a91c29d69a555c"
put {{base_url}}/63b5c03ce2a91c29d69a555c
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2FmMjM2YjZjYzExMTQ5OTlhN2FhYmMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzI4NTQzNzB9.bXUf0hDfrCb4LKwHrm_vPaXusAEN6rahe_KJ9aMHfSA

{
    "user":"63af236b6cc1114999a7aabc",
    "game":"63af23d86cc1114999a7aac4"
}

###
@objId=639ddb097207590932054f3d
put {{base_url}}/{{objId}}
Content-Type: application/json

{
    "user":"639b81d86a8df3bb367645af",
    "game":"639b8dbf6763034c6cedfb22"
}

###

post {{base_url}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzliODYxMTgzMGY0NWQ0YjA0MmYwNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzE1MzUyNTJ9.RBtLHJJKPyUPX_PS1tga1H-HEYaKax93xWcTwTJudS4


{
    "user":"639b8611830f45d4b042f061"
}

###

@objId2= 63a1a5643572df16dec0d496
delete {{base_url}}/{{objId2}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzliODYxMTgzMGY0NWQ0YjA0MmYwNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzE1MzUyNTJ9.RBtLHJJKPyUPX_PS1tga1H-HEYaKax93xWcTwTJudS4
