# USER CALLS #

@base_url=http://localhost:3000/api/auth



post {{base_url}}
Content-Type: application/json

{
    "email":"tine@test.be",
    "password":"12345"
}

###

post {{base_url}}
Content-Type: application/json

{
    
    "email":"GK1@test.be",
    "password":"12345"
}

